version: '3'
services:
  postgres:
    image: 'postgres:latest'

  redis:
    image: 'redis:latest'

  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIST_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=
      - PGHOST=
      - PGDATABASE=
      - PGPASSWORD=
      - PGPORT=
      
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app

  web:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.dev
    ports:
    - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app
  tests:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
    - /app/node_modules
    - ./frontend:/app
    command: ["npm", "run", "test"]
