apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: ghcr.io/lemonglutton/react-app:v1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred