name: Deploy Frontend on Elastic Beanstalk
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout      
        uses: actions/checkout@v2
     
      - name: Build docker image and
        run: docker build -t reactapp/react-test -f Dockerfile.dev .

      - name: Run docker image
        run: docker run -e CI=true reactapp/react-test npm test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.BEANSTALK_APP_NAME }}
          environment_name: ${{ secrets.BEANSTALK_ENV_NAME }}
          existing_bucket_name: ${{ secrets.BUCKET_NAME }}
          region: ${{ secrets.BEANSTALK_REGION }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip