name: Build and Push Image to GH CR

on:
  push: 
    branches: [ main ]

env: 
  IMAGE_NAME: reactapp/prod
  REGISTRY: ghcr.io/sdas

jobs:
  build-and-push:
    name: Build and Push to GH CR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2 

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image to GCR
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}


