name: Run tests when making PR
on:
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: frontend

jobs:
  run-unit-tests: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Debug step
        run: echo pwd

      - name: Debug step#2
        run: ls -lah

      - name: Move to frontend folder
        run: cd ./frontend

      - name: Debug step#3
        run: ls -lah

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test


