name: Tests Pull Request
on:
  pull_request:
    branches: [ main ]

jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: src, public, package.json, package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test


