name: Tests Pull Request
on:
  pull_request:
    branches: [ main ]

jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
      - name: Print content of files
        run: ls -lah

      - name: Print current working directory
        run: echo "Current working directory:\ $(pwd)"

      - name: Check if echo gonna be invoked
        run: echo "Hello all"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test


