name: Run tests when making PR

on:
  pull_request:
    branches: [main]

jobs:
  changes:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: frontend:'frontend/**'

  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test